layout_spectrum: 0.6665160837153545
typography_spectrum: 0.9357387592542991
color:
  brandStrength: 0.5748547475737067
  lightness: 0.7240970561901421
  saturation: 0.7832020247827219
  rhythmicContrast: 0.012855952340408717
  brandColors:
    - '#FFFFFF'
    - '#FFF500'
    - '#1B3582'
    - '#3BB3C3'
    - '#E57976'
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/b7a627c1-f427-4647-a8bd-8850aa9fbb55.png
name: CHILD DEVELOPMENT CENTER
url: 'https://thegrid.ai/uumcdc.com/'
navigation:
  - name: ABOUT US
    id: adf7109b-dac9-4c6f-af62-127396f5cdb2
    type: content
title: CHILD DEVELOPMENT CENTER
content: []
description: university umc
github: true
purpose:
  - type: contact
    url: 'mailto:cdc@universityumc.org'
    label: Email
  - type: contact
    url: 'tel:7027337157'
    label: Call 7027337157
